name: magmax_env
channels:
  - ursky
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - skani=0.2.2
  - megahit=1.2.9
  - spades=4.0.0
  - checkm2
  - seqtk
  - pip
  - pip:
      - tensorflow==2.4.0
