name: magma-release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run: sudo apt-get install musl musl-tools; rustup target add x86_64-unknown-linux-musl; export RUSTFLAGS="-C target-cpu=x86-64"; cargo build --release --target=x86_64-unknown-linux-musl
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            target/x86_64-unknown-linux-musl/release/magma
    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-gnu
