name: magmax-release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl musl-tools

      - name: Build binary
        run: cargo build --release --target=x86_64-unknown-linux-musl

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-unknown-linux-musl/release/magmax
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: soedinglab/MAGmax

  # build-windows:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #     - run: sudo apt-get install -y mingw-w64
  #     - run: rustup target add x86_64-pc-windows-gnu
  #     - run: cargo build --release --target x86_64-pc-windows-gnu
  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         automatic_release_tag: "latest"
  #         files: |
  #           target/x86_64-pc-windows-gnu/release/magmax

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #     - run: rustup target add x86_64-apple-darwin
  #     - run: cargo build --release --target=x86_64-apple-darwin
  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         automatic_release_tag: "latest"
  #         files: |
  #           target/x86_64-apple-darwin/release/
